//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personel_Kayit
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personel
    {
        public int personelID { get; set; }
        public string TCkimlik { get; set; }
        public string Isim { get; set; }
        public string Soyisim { get; set; }
        public string Cinsiyet { get; set; }
        public string Telefon { get; set; }
        public string Email { get; set; }
        public System.DateTime KayitTarih { get; set; }
        public int FKilceID { get; set; }
    
        public virtual Ilceler Ilceler { get; set; }
    }
}
