//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KendoCRUD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteri
    {
        public int Id { get; set; }
        public string TCkimlik { get; set; }
        public string Isim { get; set; }
        public string Soyisim { get; set; }
        public string City { get; set; }
    }
}
